function Hd = lfilter
%LFILTER Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.2 and the DSP System Toolbox 9.4.
% Generated on: 22-Mar-2018 13:21:28

% FIR Window Lowpass filter designed using the FIR1 function.

% All frequency values are in MHz.
Fs = 20;  % Sampling Frequency

N     = 10;       % Order
Fc    = 0.8;      % Cutoff Frequency
flag  = 'scale';  % Sampling Flag
Alpha = 2.5;      % Window Parameter

% Create the window vector for the design algorithm.
win = gausswin(N+1, Alpha);

% Calculate the coefficients using the FIR1 function.
b  = fir1(N, Fc/(Fs/2), 'low', win, flag);
Hd = dfilt.dffir(b);

% [EOF]
